server:
  port : ${SERVER_PORT}
  max-http-header-size: 100000
spring:
  profiles:
    include: dev
  liquibase:
    change-log: ${LIQUIBASE_CHANGELOG}
    enabled: ${LIQUIBASE_ENABLED}
  messages:
    basename: i18n.messages
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED # TRANSACTION_READ_COMMITTED / TRANSACTION_REPEATABLE_READ / TRANSACTION_SERIALIZABLE
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show-sql: false
        dialect: org.hibernate.dialect.PostgresPlusDialect
        default_schema: ${DB_SCHEMA:public}
  kafka:
    enabled: ${KAFKA_ENABLED}
    bootstrap-servers: ${KAFKA_URL}
    admin:
      properties:
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT:5000}
    consumer:
      properties:
        max.poll.interval.ms: 600000
        max.poll.records: 10
      group-id: ${KAFKA_CONSUMER_ID}
      auto-offset-reset: latest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

integration:
  order:
    burger: ${ORDER_BURGER_COMMAND_TOPIC:order-burger-command}

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE