openapi: "3.0.0"
info:
  title: Burgers API
  version: 1.0.0
  contact:
    name: Andrew
    email: andrew30511@gmail.com
paths:
  /burger:
    $ref: "./api/burger_api.yaml#/~1burger"
  /customer:
    $ref: "./api/customer_api.yaml#/~1customer"
